name: Test Secrets Access

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: self-hosted

    steps:
      - name: Check AZURE_CREDENTIALS
        run: |
          if [[ -z "${{ secrets.AZURE_CREDENTIALS }}" ]]; then
            echo "AZURE_CREDENTIALS is empty!"
          else
            echo "AZURE_CREDENTIALS is set."
            echo "${{ secrets.AZURE_CREDENTIALS }}" | wc -c
          fi

