name: Deploy .NET App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure
    runs-on: self-hosted

    steps:
      # Step 1: Install Azure CLI
      - name: Install Azure CLI
        run: |
          if ! command -v az &> /dev/null; then
            echo "Azure CLI not found. Installing..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi
          az --version

      # Step 2: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Add .NET to PATH
      - name: Add .NET to PATH
        run: |
          echo "/home/adminuser/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=/home/adminuser/.dotnet" >> $GITHUB_ENV

      # Step 4: Verify .NET Installation
      - name: Verify .NET installation
        run: dotnet --info

      # Step 5: Debug AZURE_CREDENTIALS Length
      - name: Debug Secret Content
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          if [[ -z "$AZURE_CREDENTIALS" ]]; then
            echo "AZURE_CREDENTIALS is empty!"
            exit 1
          else
            echo "AZURE_CREDENTIALS is set."
            echo "Length of AZURE_CREDENTIALS: ${#AZURE_CREDENTIALS}"
          fi

      # Step 6: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./MyWebApp/MyWebApp.csproj

      # Step 7: Build application
      - name: Build application
        run: dotnet build ./MyWebApp/MyWebApp.csproj --configuration Release

      # Step 8: Publish application
      - name: Publish application
        run: dotnet publish ./MyWebApp/MyWebApp.csproj --configuration Release --output ./publish

      # Step 9: Azure Login with Service Principal
      - name: Azure Login with Service Principal
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "Parsing AZURE_CREDENTIALS..."
          echo "$AZURE_CREDENTIALS" > azure_credentials.json
          CLIENT_ID=$(jq -r '.clientId' azure_credentials.json)
          CLIENT_SECRET=$(jq -r '.clientSecret' azure_credentials.json)
          TENANT_ID=$(jq -r '.tenantId' azure_credentials.json)
          SUBSCRIPTION_ID=$(jq -r '.subscriptionId' azure_credentials.json)

          if [[ -z "$CLIENT_ID" || -z "$CLIENT_SECRET" || -z "$TENANT_ID" || -z "$SUBSCRIPTION_ID" ]]; then
            echo "Error: Missing fields in AZURE_CREDENTIALS"
            cat azure_credentials.json
            exit 1
          fi

          echo "Logging into Azure CLI..."
          az login --service-principal \
            --username "$CLIENT_ID" \
            --password "$CLIENT_SECRET" \
            --tenant "$TENANT_ID"

          az account set --subscription "$SUBSCRIPTION_ID"
          echo "Azure login successful!"
          az account show

      # Step 10: Verify Azure Login
      - name: Verify Azure Login
        run: |
          az account show
          az account list --output table

      # Step 11: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cssstatic'
          package: ./publish

