name: Deploy .NET App to Azure App Service

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to 'main'

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure
    runs-on: self-hosted # Use your self-hosted agent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add .NET to PATH
        run: |
          echo "/home/adminuser/.dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=/home/adminuser/.dotnet" >> $GITHUB_ENV

      - name: Verify .NET installation
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore ./MyWebApp/MyWebApp.csproj

      - name: Build application
        run: dotnet build ./MyWebApp/MyWebApp.csproj --configuration Release

      - name: Publish application
        run: dotnet publish ./MyWebApp/MyWebApp.csproj --configuration Release --output ./publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cssstatic' # Replace with your Azure App Service name
          package: ./publish

