name: Deploy .NET App to Azure App Service

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to 'main'

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure
    runs-on: self-hosted # Run on your self-hosted agent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        env:
          DOTNET_ROOT: ${{ runner.temp }}/.dotnet

      - name: Update PATH for local dotnet installation
        run: echo "${{ runner.temp }}/.dotnet" >> $GITHUB_PATH

      - name: Verify .NET installation
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore ./MyWebApp/MyWebApp.csproj

      - name: Build application
        run: dotnet build ./MyWebApp/MyWebApp.csproj --configuration Release

      - name: Publish application
        run: dotnet publish ./MyWebApp/MyWebApp.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cssstatic' # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

